version: "3"
services:
  http-proxy:
    image: newcos/master-http-proxy:0.0.1
    deploy: 
      placement: 
        constraints: 
          - node.platform.os == linux
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_status.conf:/etc/nginx/conf.d/nginx_status.conf:ro \
      - /home/jgonzalez/images:/ceci
    networks:
      - dmz  
    # command: [nginx-debug, '-g', 'daemon off;']
networks:
  dmz:
    external: true
