      # Add specified repository from sources list.
      - apt_repository:
          repo: deb http://01.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse 
          state: present
        become: yes

      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic main restricted
          state: present
        become: yes

      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted
          state: present
        become: yes  

      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic universe
          state: present
        become: yes  
 
      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic multiverse
          state: present 
        become: yes

      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic-updates multiverse
          state: present 
        become: yes

      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic-updates universe
          state: present 
        become: yes
      
      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
          state: present 
        become: yes

      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic-security main restricted
          state: present 
        become: yes

      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic-security universe
          state: present 
        become: yes

      - apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu bionic-security multiverse
          state: present   
        become: yes