      # Add specified repository from sources list.
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
      become: yes

    - name: Install a list of packages
      apt:
        pkg:
        - nmap
        - docker-compose
        - vim
        - nodejs
        - npm
        - htop
        #- git
        #- ansible
      become: yes
      when: '"nfs" not in ansible_hostname'