version: '3'
services:
  prometheus:
    image: prom/prometheus
    deploy: 
      placement: 
        constraints: 
          - node.platform.os == linux
    ports:
     - 9092:9090
    networks:
      - dmz_ssl
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  nginx-exporter:
    image: fish/nginx-exporter
    # image: nginx/nginx-prometheus-exporter:0.8.0
    container_name: 'nginx_exporter'
    command:
      - '-nginx.scrape_uri=http://http-proxy:8080/stub_status'
    ports:
      - '9113:9113'
    networks:
      - dmz_ssl

  node_exporter:
    image: 'quay.io/prometheus/node-exporter'
    container_name: 'node_exporter'
    ports:
      - '9100:9100'
    networks:
      - dmz_ssl

networks:
  dmz_ssl:
    external: true
