--- 
    alerting: 
      alertmanagers: 
        - 
          static_configs: 
            - 
              targets: ~
    global: 
      evaluation_interval: 15s
      scrape_interval: 15s
    rule_files: ~
    scrape_configs: 
      - 
        job_name: jenkins
        metrics_path: /prometheus
        static_configs: 
          - targets: ['jenkins-cicd_jenkins:8080']

      - job_name: 'Prometheus'
        static_configs:
          - targets: ['prometheus:9090']

      - job_name: 'NginxExporter'
        static_configs:
          - targets: ['qwerty.com.ar:9113']          
      
      - job_name: 'NodeExporter'
        static_configs:
          - targets: ['node_exporter:9100']
    
    #   - job_name: 'Grafana'
    #     static_configs:
    #       - targets: ['ip_adress:3000']
    
