version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      # - /shared/newcos-portainer/data:/data
      - portainer_data:/data
    networks:
      - agent_network
      - dmz
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager, node.hostname == newcos-manager-01]

  # portainer_agent: # windows agents
  #   image: portainer/agent:windows1803-amd64
  #   volumes:
  #     - \\.\pipe\docker_engine:\\.\pipe\docker_engine
  #   ports:
  #     - target: 9001
  #       published: 9001
  #       protocol: tcp
  #       mode: host
  #   networks:
  #     - agent_network 
  #   environment:
  #     AGENT_CLUSTER_ADDR: "tasks.agent portainer/agent"   
  #   deploy:
  #     placement:
  #       constraints: [node.platform.os == windows]

networks:
  agent_network:
    driver: overlay
    attachable: true
  dmz:
    external: true

volumes:
  portainer_data:
