version: "3"
services:
  http-proxy:
    #image: harbor-01.newtech.com.ar/newcos-teams/master-http-proxy:0.0.1
    image: newcos/master-http-proxy:0.0.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /shared/master-http-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /shared/master-http-proxy/nginx.conf:/etc/nginx/nginx.conf
      - /shared/master-http-proxy/nginx_status.conf:/etc/nginx/conf.d/nginx_status.conf:ro \
      - /shared/master-http-proxy/certs/newcos.crt:/etc/ssl/newcos.crt
      - /shared/master-http-proxy/certs/newcos.rsa:/etc/ssl/newcos.rsa
      - /shared/master-http-proxy/custom-errors/custom_errors.conf:/etc/nginx/custom-errors.conf
      - /shared/master-http-proxy/custom-errors/404.html:/usr/share/nginx/html/404.html
      - /shared/master-http-proxy/custom-errors/50x.html:/usr/share/nginx/html/50x.html
    networks:
      - dmz  
      - dmz_ypf
networks:
  dmz:
    external: true
  dmz_ypf:
    external: true
