version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    # ports:
       #- 3000:3000
    networks:
      - monitoring
      - dmz_ssl
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      - VIRTUAL_HOST=grafana.qwerty.com.ar
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.qwerty.com.ar
      - LETSENCRYPT_EMAIL=joagonzalez@gmail.com  

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
      
networks:
  monitoring:
  dmz_ssl:
    external: True      
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
