version: '3'

services:

  registry:
    image: registry:2
    restart: always
    expose:
      - "5000"
    networks:
      - registry_net
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_HOST: docker.peladonerd.com
      REGISTRY_HTTP_ADDR: :5000
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm" 
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert.pem
      REGISTRY_HTTP_TLS_KEY: /certs/key.pem
      LETSENCRYPT_HOST: docker.peladonerd.com
      LETSENCRYPT_EMAIL: pablo@peladonerd.com
      # REGISTRY_STORAGE: s3
      # REGISTRY_STORAGE_S3_ACCESSKEY: <api access key>
      # REGISTRY_STORAGE_S3_SECRETKEY: <api secret>
      # REGISTRY_STORAGE_S3_BUCKET: <bucket name>
      # REGISTRY_STORAGE_S3_REGION: <region>
      # REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: false
    volumes:
      - ./auth:/auth
      - /docker_registry:/var/lib/registry
      - ./certs:/certs

  # We are using these 2 containers because automatic TLS certs from docker registry don't work
  # Estamos usando estos 2 contenedores porque los certs automaticos con docker registry no funcionan
  # https://github.com/docker/distribution/issues/2545


  ui:
    image: jc21/registry-ui
    expose:
      - "80"
    networks:
      - registry_net
    environment:
      REGISTRY_HOST: registry:5000
      REGISTRY_SSL: "true"
      REGISTRY_DOMAIN: registry.qwerty.com.ar
      # Tienes que crear este usuario para que ui se pueda conectar al registry con auth
      # You gotta create this user for the ui to connect to the registry using auth
      REGISTRY_USER: docker
      REGISTRY_PASS: delfoxete87
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    restart: always
    links:
      - registry:docker.peladonerd.com

  proxy:
    image: nginx
    expose:
      - "80"
    networks:
      - dmz_ssl
      - registry_net
    environment:
      - VIRTUAL_HOST=registry.qwerty.com.ar
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=registry.qwerty.com.ar
      - LETSENCRYPT_EMAIL=joagonzalez@gmail.com
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    depends_on:
      - ui
      - registry
      #- nginx-proxy
    links:
      - ui
      - registry
    restart: always

networks: 
  dmz_ssl:
    external: true
  registry_net:
