--- 
  alerting: 
    alertmanagers: 
      - 
        static_configs: 
          - 
            targets: ~
  global: 
    evaluation_interval: 15s
    scrape_interval: 15s
  rule_files: ~
  scrape_configs: 
    - 
      job_name: prometheus
      static_configs: 
        - 
          targets: 
            - "cluster.smq.net:9090"
    - 
      job_name: jenkins
      metrics_path: /prometheus
      static_configs: 
        - targets: ['cluster.smq.net:8090']
  